services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/service
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
